<?php
$form = $this->form;
$form->prepare();
?>
<h1>Edit blog post</h1>

<?php echo $this->form()->openTag($form); // <form action...> ?>

<div class="form-group">
    <?php echo $this->formRow($form->get('title')); ?>
</div>
<div class="form-group">
    <?php echo $this->formRow($form->get('slug')); ?>
</div>
<div class="form-group">
    <?php echo $this->formRow($form->get('content')); ?>
</div>
<div class="form-group">
    <?php echo $this->formRow($form->get('category_id')); ?>
</div>

<?php echo $this->formRow($form->get('id')); ?>
<?php echo $this->formSubmit($form->get('submit')); ?>
<?php echo $this->form()->closeTag(); // </form> ?>
