<h1>New user</h1>

<?php
  $form = $this->form;
  $form->prepare();
  echo $this->form()->openTag($form); // <form>
?>

<div class="form-group">
  <?php echo $this->formRow($form->get('firstName')); ?>
</div>
<div class="form-group">
  <?php echo $this->formRow($form->get('lastName')); ?>
</div>
<div class="form-group">
  <?php echo $this->formRow($form->get('email')); ?>
</div>
<div class="form-group">
  <?php echo $this->formRow($form->get('password')); ?>
</div>
<div class="form-group">
  <?php echo $this->formRow($form->get('repeatPassword')); ?>
</div>

<?php echo $this->formSubmit($form->get('submit')); ?>
<?php echo $this->form()->closeTag(); // </form>
